module.exports.competitions = [{
    id: 426,
    caption: "Premier League 2016/17",
    league: "PL",
    year: "2016",
    currentMatchday: 4,
    numberOfMatchdays: 38,
    numberOfTeams: 20,
    numberOfGames: 380,
    lastUpdated: "2016-09-09T00:00:22Z"
},
    {
        id: 426,
        caption: "Premier League 2016/17",
        league: "PL",
        year: "2016",
        currentMatchday: 4,
        numberOfMatchdays: 38,
        numberOfTeams: 20,
        numberOfGames: 380,
        lastUpdated: "2016-09-09T00:00:22Z"
    },
    {
        id: 427,
        caption: "Championship 2016/17",
        league: "ELC",
        year: "2016",
        currentMatchday: 6,
        numberOfMatchdays: 46,
        numberOfTeams: 24,
        numberOfGames: 552,
        lastUpdated: "2016-09-09T00:00:50Z"
    },
    {
        id: 428,
        caption: "League One 2016/17",
        league: "EL1",
        year: "2016",
        currentMatchday: 7,
        numberOfMatchdays: 46,
        numberOfTeams: 24,
        numberOfGames: 552,
        lastUpdated: "2016-09-09T00:01:45Z"
    },
    {
        id: 430,
        caption: "1. Bundesliga 2016/17",
        league: "BL1",
        year: "2016",
        currentMatchday: 2,
        numberOfMatchdays: 34,
        numberOfTeams: 18,
        numberOfGames: 306,
        lastUpdated: "2016-09-09T00:02:19Z"
    },
    {
        id: 431,
        caption: "2. Bundesliga 2016/17",
        league: "BL2",
        year: "2016",
        currentMatchday: 4,
        numberOfMatchdays: 34,
        numberOfTeams: 18,
        numberOfGames: 306,
        lastUpdated: "2016-09-09T00:02:51Z"
    }
];

module.exports.standing = [{
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/65"}},
    "position": 1,
    "teamName": "Manchester City FC",
    "crestURI": "https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg",
    "playedGames": 3,
    "points": 9,
    "goals": 9,
    "goalsAgainst": 3,
    "goalDifference": 6,
    "wins": 3,
    "draws": 0,
    "losses": 0,
    "home": {"goals": 5, "goalsAgainst": 2, "wins": 2, "draws": 0, "losses": 0},
    "away": {"goals": 4, "goalsAgainst": 1, "wins": 1, "draws": 0, "losses": 0}
}, {
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/61"}},
    "position": 2,
    "teamName": "Chelsea FC",
    "crestURI": "http://upload.wikimedia.org/wikipedia/de/5/5c/Chelsea_crest.svg",
    "playedGames": 3,
    "points": 9,
    "goals": 7,
    "goalsAgainst": 2,
    "goalDifference": 5,
    "wins": 3,
    "draws": 0,
    "losses": 0,
    "home": {"goals": 5, "goalsAgainst": 1, "wins": 2, "draws": 0, "losses": 0},
    "away": {"goals": 2, "goalsAgainst": 1, "wins": 1, "draws": 0, "losses": 0}
}, {
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/66"}},
    "position": 3,
    "teamName": "Manchester United FC",
    "crestURI": "http://upload.wikimedia.org/wikipedia/de/d/da/Manchester_United_FC.svg",
    "playedGames": 3,
    "points": 9,
    "goals": 6,
    "goalsAgainst": 1,
    "goalDifference": 5,
    "wins": 3,
    "draws": 0,
    "losses": 0,
    "home": {"goals": 2, "goalsAgainst": 0, "wins": 1, "draws": 0, "losses": 0},
    "away": {"goals": 4, "goalsAgainst": 1, "wins": 2, "draws": 0, "losses": 0}
}, {
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/62"}},
    "position": 4,
    "teamName": "Everton FC",
    "crestURI": "http://upload.wikimedia.org/wikipedia/de/f/f9/Everton_FC.svg",
    "playedGames": 3,
    "points": 7,
    "goals": 4,
    "goalsAgainst": 2,
    "goalDifference": 2,
    "wins": 2,
    "draws": 1,
    "losses": 0,
    "home": {"goals": 2, "goalsAgainst": 1, "wins": 1, "draws": 1, "losses": 0},
    "away": {"goals": 2, "goalsAgainst": 1, "wins": 1, "draws": 0, "losses": 0}
}, {
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/322"}},
    "position": 5,
    "teamName": "Hull City FC",
    "crestURI": "http://upload.wikimedia.org/wikipedia/de/a/a9/Hull_City_AFC.svg",
    "playedGames": 3,
    "points": 6,
    "goals": 4,
    "goalsAgainst": 2,
    "goalDifference": 2,
    "wins": 2,
    "draws": 0,
    "losses": 1,
    "home": {"goals": 2, "goalsAgainst": 2, "wins": 1, "draws": 0, "losses": 1},
    "away": {"goals": 2, "goalsAgainst": 0, "wins": 1, "draws": 0, "losses": 0}
}, {
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/343"}},
    "position": 6,
    "teamName": "Middlesbrough FC",
    "crestURI": "https://upload.wikimedia.org/wikipedia/en/2/2c/Middlesbrough_FC_crest.svg",
    "playedGames": 3,
    "points": 5,
    "goals": 3,
    "goalsAgainst": 2,
    "goalDifference": 1,
    "wins": 1,
    "draws": 2,
    "losses": 0,
    "home": {"goals": 1, "goalsAgainst": 1, "wins": 0, "draws": 1, "losses": 0},
    "away": {"goals": 2, "goalsAgainst": 1, "wins": 1, "draws": 1, "losses": 0}
}, {
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/73"}},
    "position": 6,
    "teamName": "Tottenham Hotspur FC",
    "crestURI": "http://upload.wikimedia.org/wikipedia/de/b/b4/Tottenham_Hotspur.svg",
    "playedGames": 3,
    "points": 5,
    "goals": 3,
    "goalsAgainst": 2,
    "goalDifference": 1,
    "wins": 1,
    "draws": 2,
    "losses": 0,
    "home": {"goals": 2, "goalsAgainst": 1, "wins": 1, "draws": 1, "losses": 0},
    "away": {"goals": 1, "goalsAgainst": 1, "wins": 0, "draws": 1, "losses": 0}
}, {
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/57"}},
    "position": 8,
    "teamName": "Arsenal FC",
    "crestURI": "http://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg",
    "playedGames": 3,
    "points": 4,
    "goals": 6,
    "goalsAgainst": 5,
    "goalDifference": 1,
    "wins": 1,
    "draws": 1,
    "losses": 1,
    "home": {"goals": 3, "goalsAgainst": 4, "wins": 0, "draws": 0, "losses": 1},
    "away": {"goals": 3, "goalsAgainst": 1, "wins": 1, "draws": 1, "losses": 0}
}, {
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/338"}},
    "position": 9,
    "teamName": "Leicester City FC",
    "crestURI": "http://upload.wikimedia.org/wikipedia/en/6/63/Leicester02.png",
    "playedGames": 3,
    "points": 4,
    "goals": 3,
    "goalsAgainst": 3,
    "goalDifference": 0,
    "wins": 1,
    "draws": 1,
    "losses": 1,
    "home": {"goals": 2, "goalsAgainst": 1, "wins": 1, "draws": 1, "losses": 0},
    "away": {"goals": 1, "goalsAgainst": 2, "wins": 0, "draws": 0, "losses": 1}
}, {
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/74"}},
    "position": 10,
    "teamName": "West Bromwich Albion FC",
    "crestURI": "http://upload.wikimedia.org/wikipedia/de/8/8b/West_Bromwich_Albion.svg",
    "playedGames": 3,
    "points": 4,
    "goals": 2,
    "goalsAgainst": 2,
    "goalDifference": 0,
    "wins": 1,
    "draws": 1,
    "losses": 1,
    "home": {"goals": 1, "goalsAgainst": 2, "wins": 0, "draws": 1, "losses": 1},
    "away": {"goals": 1, "goalsAgainst": 0, "wins": 1, "draws": 0, "losses": 0}
}, {
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/64"}},
    "position": 11,
    "teamName": "Liverpool FC",
    "crestURI": "http://upload.wikimedia.org/wikipedia/de/0/0a/FC_Liverpool.svg",
    "playedGames": 3,
    "points": 4,
    "goals": 5,
    "goalsAgainst": 6,
    "goalDifference": -1,
    "wins": 1,
    "draws": 1,
    "losses": 1,
    "home": {"goals": 0, "goalsAgainst": 0, "wins": 0, "draws": 0, "losses": 0},
    "away": {"goals": 5, "goalsAgainst": 6, "wins": 1, "draws": 1, "losses": 1}
}, {
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/563"}},
    "position": 12,
    "teamName": "West Ham United FC",
    "crestURI": "http://upload.wikimedia.org/wikipedia/de/e/e0/West_Ham_United_FC.svg",
    "playedGames": 3,
    "points": 3,
    "goals": 3,
    "goalsAgainst": 5,
    "goalDifference": -2,
    "wins": 1,
    "draws": 0,
    "losses": 2,
    "home": {"goals": 1, "goalsAgainst": 0, "wins": 1, "draws": 0, "losses": 0},
    "away": {"goals": 2, "goalsAgainst": 5, "wins": 0, "draws": 0, "losses": 2}
}, {
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/328"}},
    "position": 13,
    "teamName": "Burnley FC",
    "crestURI": "https://upload.wikimedia.org/wikipedia/en/0/02/Burnley_FC_badge.png",
    "playedGames": 3,
    "points": 3,
    "goals": 2,
    "goalsAgainst": 4,
    "goalDifference": -2,
    "wins": 1,
    "draws": 0,
    "losses": 2,
    "home": {"goals": 2, "goalsAgainst": 1, "wins": 1, "draws": 0, "losses": 1},
    "away": {"goals": 0, "goalsAgainst": 3, "wins": 0, "draws": 0, "losses": 1}
}, {
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/72"}},
    "position": 13,
    "teamName": "Swansea City FC",
    "crestURI": "http://upload.wikimedia.org/wikipedia/de/a/ab/Swansea_City_Logo.svg",
    "playedGames": 3,
    "points": 3,
    "goals": 2,
    "goalsAgainst": 4,
    "goalDifference": -2,
    "wins": 1,
    "draws": 0,
    "losses": 2,
    "home": {"goals": 0, "goalsAgainst": 2, "wins": 0, "draws": 0, "losses": 1},
    "away": {"goals": 2, "goalsAgainst": 2, "wins": 1, "draws": 0, "losses": 1}
}, {
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/340"}},
    "position": 15,
    "teamName": "Southampton FC",
    "crestURI": "http://upload.wikimedia.org/wikipedia/de/c/c9/FC_Southampton.svg",
    "playedGames": 3,
    "points": 2,
    "goals": 2,
    "goalsAgainst": 4,
    "goalDifference": -2,
    "wins": 0,
    "draws": 2,
    "losses": 1,
    "home": {"goals": 2, "goalsAgainst": 2, "wins": 0, "draws": 2, "losses": 0},
    "away": {"goals": 0, "goalsAgainst": 2, "wins": 0, "draws": 0, "losses": 1}
}, {
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/71"}},
    "position": 16,
    "teamName": "Sunderland AFC",
    "crestURI": "http://upload.wikimedia.org/wikipedia/de/6/60/AFC_Sunderland.svg",
    "playedGames": 3,
    "points": 1,
    "goals": 3,
    "goalsAgainst": 5,
    "goalDifference": -2,
    "wins": 0,
    "draws": 1,
    "losses": 2,
    "home": {"goals": 1, "goalsAgainst": 2, "wins": 0, "draws": 0, "losses": 1},
    "away": {"goals": 2, "goalsAgainst": 3, "wins": 0, "draws": 1, "losses": 1}
}, {
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/354"}},
    "position": 17,
    "teamName": "Crystal Palace FC",
    "crestURI": "http://upload.wikimedia.org/wikipedia/de/b/bf/Crystal_Palace_F.C._logo_(2013).png",
    "playedGames": 3,
    "points": 1,
    "goals": 1,
    "goalsAgainst": 3,
    "goalDifference": -2,
    "wins": 0,
    "draws": 1,
    "losses": 2,
    "home": {"goals": 1, "goalsAgainst": 2, "wins": 0, "draws": 1, "losses": 1},
    "away": {"goals": 0, "goalsAgainst": 1, "wins": 0, "draws": 0, "losses": 1}
}, {
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/346"}},
    "position": 18,
    "teamName": "Watford FC",
    "crestURI": "https://upload.wikimedia.org/wikipedia/en/e/e2/Watford.svg",
    "playedGames": 3,
    "points": 1,
    "goals": 3,
    "goalsAgainst": 6,
    "goalDifference": -3,
    "wins": 0,
    "draws": 1,
    "losses": 2,
    "home": {"goals": 2, "goalsAgainst": 5, "wins": 0, "draws": 0, "losses": 2},
    "away": {"goals": 1, "goalsAgainst": 1, "wins": 0, "draws": 1, "losses": 0}
}, {
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/1044"}},
    "position": 19,
    "teamName": "AFC Bournemouth",
    "crestURI": "https://upload.wikimedia.org/wikipedia/de/4/41/Afc_bournemouth.svg",
    "playedGames": 3,
    "points": 1,
    "goals": 2,
    "goalsAgainst": 5,
    "goalDifference": -3,
    "wins": 0,
    "draws": 1,
    "losses": 2,
    "home": {"goals": 1, "goalsAgainst": 3, "wins": 0, "draws": 0, "losses": 1},
    "away": {"goals": 1, "goalsAgainst": 2, "wins": 0, "draws": 1, "losses": 1}
}, {
    "_links": {"team": {"href": "http://api.football-data.org/v1/teams/70"}},
    "position": 20,
    "teamName": "Stoke City FC",
    "crestURI": "http://upload.wikimedia.org/wikipedia/de/a/a3/Stoke_City.svg",
    "playedGames": 3,
    "points": 1,
    "goals": 2,
    "goalsAgainst": 6,
    "goalDifference": -4,
    "wins": 0,
    "draws": 1,
    "losses": 2,
    "home": {"goals": 1, "goalsAgainst": 4, "wins": 0, "draws": 0, "losses": 1},
    "away": {"goals": 1, "goalsAgainst": 2, "wins": 0, "draws": 1, "losses": 1}
}];

module.exports.fixtures = [{
    "id": 150841,
    "competitionId": 426,
    "date": "2016-08-13T11:30:00Z",
    "status": "FINISHED",
    "matchday": 1,
    "homeTeamName": "Hull City FC",
    "homeTeamId": 322,
    "awayTeamName": "Leicester City FC",
    "awayTeamId": 338,
    "result": {"goalsHomeTeam": 2, "goalsAwayTeam": 1},
    "odds": {"homeWin": 3.25, "draw": 3.25, "awayWin": 2.2}
}];

module.exports.teams = [{
    "id": 322,
    "name": "Hull City FC",
    "shortName": "Hull",
    "squadMarketValue": "122,250,000 €",
    "crestUrl": "http://upload.wikimedia.org/wikipedia/de/a/a9/Hull_City_AFC.svg"
}, {
    "id": 338,
    "name": "Leicester City FC",
    "shortName": "Foxes",
    "squadMarketValue": "210,500,000 €",
    "crestUrl": "http://upload.wikimedia.org/wikipedia/en/6/63/Leicester02.png"
}]